// Pulls ABIs out of the Foundry artifacts next door and writes them as a typed
// module. Run after `forge build` in the repo root; the output is committed so
// the web app builds without a Solidity toolchain.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../out");

const CONTRACTS = [
  ["Launchpad", "Launchpad.sol"],
  ["BlockHook", "BlockHook.sol"],
  ["PotVault", "PotVault.sol"],
  ["BoundedRouter", "BoundedRouter.sol"],
  ["BondingCurve", "BondingCurve.sol"],
  ["LaunchToken", "LaunchToken.sol"],
  ["PoolManager", "PoolManager.sol"],
];

let body = `// GENERATED by scripts/gen-abi.mjs — do not edit by hand.\n`;
body += `// Source: Foundry artifacts in ../out. Regenerate with \`npm run gen:abi\`.\n\n`;

for (const [name, file] of CONTRACTS) {
  const artifact = JSON.parse(
    readFileSync(resolve(out, file, `${name}.json`), "utf8"),
  );
  body += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}

mkdirSync(resolve(here, "../src/lib"), { recursive: true });
writeFileSync(resolve(here, "../src/lib/abi.ts"), body);
console.log(`wrote src/lib/abi.ts (${CONTRACTS.length} contracts)`);
